<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipeIngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('recipe_ingredient')->insert([
            ['recipe_id' => 1, 'ingredient_id' => 1, 'unit_id' => 1, 'quantity' => '300', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 2, 'unit_id' => 2, 'quantity' => '4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 3, 'unit_id' => 2, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 4, 'unit_id' => 3, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 5, 'unit_id' => 4, 'quantity' => '300', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 6, 'unit_id' => 5, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 7, 'unit_id' => 6, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 8, 'unit_id' => 6, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 9, 'unit_id' => 6, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 10, 'unit_id' => 6, 'quantity' => '3', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 1, 'ingredient_id' => 11, 'unit_id' => 6, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 12, 'unit_id' => 1, 'quantity' => '150', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 13, 'unit_id' => 8, 'quantity' => '5', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 4, 'unit_id' => 3, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 14, 'unit_id' => 3, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 15, 'unit_id' => 3, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 16, 'unit_id' => 7, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 5, 'unit_id' => 4, 'quantity' => '800', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 6, 'unit_id' => 5, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 17, 'unit_id' => 6, 'quantity' => '4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 2, 'ingredient_id' => 11, 'unit_id' => 6, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 3, 'ingredient_id' => 18, 'unit_id' => 2, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 3, 'ingredient_id' => 19, 'unit_id' => 2, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 3, 'ingredient_id' => 20, 'unit_id' => 9, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 3, 'ingredient_id' => 21, 'unit_id' => 5, 'quantity' => '1/4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 3, 'ingredient_id' => 11, 'unit_id' => 6, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 3, 'ingredient_id' => 22, 'unit_id' => 5, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 3, 'ingredient_id' => 23, 'unit_id' => 5, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 3, 'ingredient_id' => 5, 'unit_id' => 5, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 24, 'unit_id' => 7, 'quantity' => '10', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 25, 'unit_id' => 1, 'quantity' => '100', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 26, 'unit_id' => 7, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 4, 'unit_id' => 3, 'quantity' => '1/4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 14, 'unit_id' => 8, 'quantity' => '5', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 27, 'unit_id' => 10, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 20, 'unit_id' => 9, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 5, 'unit_id' => 4, 'quantity' => '400', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 10, 'unit_id' => 5, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 4, 'ingredient_id' => 21, 'unit_id' => 5, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 12, 'unit_id' => 1, 'quantity' => '80', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 28, 'unit_id' => 1, 'quantity' => '50', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 29, 'unit_id' => 11, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 19, 'unit_id' => 2, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 30, 'unit_id' => 3, 'quantity' => '3', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 31, 'unit_id' => 3, 'quantity' => '1/4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 22, 'unit_id' => 5, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 5, 'unit_id' => 4, 'quantity' => '300', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 32, 'unit_id' => 6, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 21, 'unit_id' => 5, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 5, 'ingredient_id' => 17, 'unit_id' => 6, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 33, 'unit_id' => 1, 'quantity' => '80', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 34, 'unit_id' => 1, 'quantity' => '100', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 4, 'unit_id' => 3, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 35, 'unit_id' => 2, 'quantity' => '1/4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 30, 'unit_id' => 12, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 36, 'unit_id' => 2, 'quantity' => '4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 10, 'unit_id' => 6, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 8, 'unit_id' => 6, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 9, 'unit_id' => 5, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 37, 'unit_id' => 14, 'quantity' => '少々', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 27, 'unit_id' => 14, 'quantity' => '少々', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 6, 'ingredient_id' => 22, 'unit_id' => 6, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 38, 'unit_id' => 7, 'quantity' => '6', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 39, 'unit_id' => 13, 'quantity' => '適量', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 40, 'unit_id' => 1, 'quantity' => '150', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 3, 'unit_id' => 2, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 41, 'unit_id' => 6, 'quantity' => '1〜2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 42, 'unit_id' => 6, 'quantity' => '1〜2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 37, 'unit_id' => 14, 'quantity' => '少々', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 43, 'unit_id' => 1, 'quantity' => '20', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 44, 'unit_id' => 1, 'quantity' => '20', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 45, 'unit_id' => 4, 'quantity' => '200', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 7, 'ingredient_id' => 46, 'unit_id' => 14, 'quantity' => '少々', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 8, 'ingredient_id' => 19, 'unit_id' => 2, 'quantity' => '5', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 8, 'ingredient_id' => 47, 'unit_id' => 7, 'quantity' => '4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 8, 'ingredient_id' => 48, 'unit_id' => 15, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 8, 'ingredient_id' => 35, 'unit_id' => 2, 'quantity' => '1/4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 8, 'ingredient_id' => 45, 'unit_id' => 6, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 8, 'ingredient_id' => 49, 'unit_id' => 6, 'quantity' => '3', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 8, 'ingredient_id' => 20, 'unit_id' => 5, 'quantity' => '1/3', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 8, 'ingredient_id' => 50, 'unit_id' => 14, 'quantity' => '少々', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 8, 'ingredient_id' => 51, 'unit_id' => 6, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 9, 'ingredient_id' => 19, 'unit_id' => 2, 'quantity' => '4', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 9, 'ingredient_id' => 2, 'unit_id' => 2, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 9, 'ingredient_id' => 3, 'unit_id' => 2, 'quantity' => '1/2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 9, 'ingredient_id' => 51, 'unit_id' => 6, 'quantity' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 9, 'ingredient_id' => 20, 'unit_id' => 5, 'quantity' => '1/3', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 9, 'ingredient_id' => 50, 'unit_id' => 14, 'quantity' => '少々', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 10, 'ingredient_id' => 52, 'unit_id' => 1, 'quantity' => '100', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 10, 'ingredient_id' => 53, 'unit_id' => 7, 'quantity' => '5', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 10, 'ingredient_id' => 43, 'unit_id' => 1, 'quantity' => '10', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 10, 'ingredient_id' => 44, 'unit_id' => 6, 'quantity' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 10, 'ingredient_id' => 45, 'unit_id' => 4, 'quantity' => '200', 'created_at' => now(), 'updated_at' => now()],
            ['recipe_id' => 10, 'ingredient_id' => 46, 'unit_id' => 14, 'quantity' => '少々', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
